### ISSUE TITLE
User can access the view which shows data and choose days

### ISSUE THREAD

**Issue by JoshuaAaronBaker** [JoshuaAaronBaker/Daily-Dose-of-Space#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click a button to access a calendar which will trigger the api and load in data
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="615" alt="Screen Shot 2022-08-04 at 7 57 49 AM" src="https://user-images.githubusercontent.com/91937935/182880049-6430236e-123d-4343-a4a5-5f11a01ee7e6.png">
<img width="773" alt="Screen Shot 2022-08-04 at 7 58 29 AM" src="https://user-images.githubusercontent.com/91937935/182880061-075ceff7-2178-43c2-8ee6-8c4899f512c2.png">
<img width="773" alt="Screen Shot 2022-08-04 at 7 58 39 AM" src="https://user-images.githubusercontent.com/91937935/182880065-b5f1595f-350a-4156-84bd-6556a9f4cf21.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Set up home page including buttons.
- [x] Target button (click me) for click event .
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Swap to view that holds that data when (click me) button is pressed.
- [x] write HTML and CSS to structure the format of the view.
- [x] Populate the view with data from the api.
- [x] Add an input of type date that lets the user select a specific date.
- [x] when the date is changed, update the information displayed to match the date.
- [x] Remove all commented out code.
