### ISSUE TITLE
User can save images

### ISSUE THREAD

**Issue by JoshuaAaronBaker** [JoshuaAaronBaker/Daily-Dose-of-Space#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-08-05 at 3 26 19 PM](https://user-images.githubusercontent.com/91937935/183219556-24e937ff-bef3-4916-afb9-1e94c9b39e83.png)
![Screen Shot 2022-08-05 at 3 26 01 PM](https://user-images.githubusercontent.com/91937935/183219636-621e9dcf-77f3-48d1-8e7c-728700702039.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Make a save button
- [x] Adjust HTML and CSS styling/format to account for the save button
- [x] Make the button clickable
- [x] Make an array to hold the grouped data
- [x] Make an object to group the data 
- [x] When the button is clicked store the current information(including image, name, date, and description) in local storage
- [x] Clean up any CSS that is not needed
