### ISSUE TITLE
User can view their saved images

### ISSUE THREAD

**Issue by JoshuaAaronBaker** [JoshuaAaronBaker/Daily-Dose-of-Space#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##

<img width="396" alt="Screen Shot 2022-08-12 at 7 52 05 AM" src="https://user-images.githubusercontent.com/91937935/184384002-13138c89-2fce-45fc-a4fe-98dd3b1e776b.png">
<img width="772" alt="Screen Shot 2022-08-12 at 7 53 15 AM" src="https://user-images.githubusercontent.com/91937935/184384021-0e81af78-cdf9-481d-a2dc-39b0e7f3ff21.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Create an anchor tab and put it in the nav bar for saved images
- [x] Create a view for the saved images page
- [x] Make the HTML and CSS for the view saved images page
- [x] Make a DOM Tree to generate the Images inside the page with the proper layout
- [x] Show only the images, in a grid layout within the saved images page
- [x] Make each image clickable
- [x] Make the HTML and CSS for a modal
- [x] When the image is clicked, display a modal popup window with all the information including the image, date, title, and explanation of the image that was clicked
