### ISSUE TITLE
User can remove a saved image

### ISSUE THREAD

**Issue by JoshuaAaronBaker** [JoshuaAaronBaker/Daily-Dose-of-Space#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="757" alt="Screen Shot 2022-08-14 at 3 28 42 PM" src="https://user-images.githubusercontent.com/91937935/184557180-5abac91d-188d-4949-9661-b47a90752009.png">
<img width="188" alt="Screen Shot 2022-08-14 at 3 36 22 PM" src="https://user-images.githubusercontent.com/91937935/184557352-9aa834bc-2f1a-4b25-a13b-213618c100ed.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] ...
- [x] Add remove button to the modal view that shows all info
- [x] Make the remove button clickable
- [x] Modify HTML and CSS in order to style the button
- [x] Write a function that will remove the image displayed in the modal view from local storage when the remove button is clicked
- [x] Clean up CSS
